### ISSUE TITLE
Collaboration to create a GTK builder like project

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#24] opened 2015-02-20 10:05 UTC
Scratch all the previous issues I opened before and let's discuss here first whether it would be good to have some kind of collaboration. First thing to point is that my previous issues where kind of proposals to know your opinions on the different topics for my specific use case.

I think this project is quite a good starting point in order to have something like jhbuild for windows where one can build their specific libraries or projects by using this powershell script.

Instead of just forking the project and do some stuff I'd really prefer to have it as a joined project where we would join effords also with upstream gtk people.

My main goals is to be able to easily build gtk3 and maybe some other libraries. Keeping everything in a way so I can build just a library or a library with the specific deps without the need of building everything. Also I would like to convert this in the way of getting some decent GTK binaries for MSVC.

I am adding @fanc999 since he is the current maintainer of the GTK mvsc projects, in case he wants to add something to this.

**Comment by Arnavion** [comment] 2015-02-20 10:37
Note that the current maintainers (the HexChat devs) will never use this bundle for anything except building HC. That means that:

- If something breaks in a component not used by HC, we won't care to patch it.

- If something breaks in a component used by HC, we'll patch it, potentially breaking something else not used by HC. Eg: [patches that fix bugs in upstream,](https://github.com/hexchat/gtk-win32/blob/master/pango/pango-synthesize-fonts-properly.patch) [patches that revert upstream commits because they broke HC,](https://github.com/hexchat/gtk-win32/blob/master/gtk/gtk-revert-scrolldc-commit.patch) [patches that never got accepted by upstream, ](https://github.com/hexchat/gtk-win32/tree/master/gtk) etc.

- We'll tweak the build in ways that continue to build everything needed for HC, but maybe not anything else. Eg: [removing stuff from openssl](https://github.com/hexchat/gtk-win32/commit/611a2f1) (although this particular example is a good thing), not compiling tests for projects, etc.

I personally don't care to increase the amount of work I put into this project, which currently is check every 2-4 weeks for updated dependencies -> download and diff their files -> update project files -> find project files are broken -> fix project files -> build everything -> [find HC is broken -> debug HC -> make patch to fix something] -> repeat.

In particular, you want to build gtk3 and some new deps, and I absolutely don't want to take responsibility for fixing bugs in them.

This project must continue to be the repository used to build gtk2 for HC. So, options:

1. Add you / Fan as maintainers to this project. You maintain your libs and any deps, and you promise that any changes you make will not break HC, and that changes required to fix HC have priority.

1. You maintain your separate repository on top of this one as you are now. If we do something here because of HC that breaks you, handling it is your problem.

I am inclined to go with option 2 for the reasons I gave above, but I'm open to being convinced otherwise.

**Comment by nacho** [comment] 2015-02-20 11:44
Thanks a lot about your comment, there is a lot of content on it so I will try to tackle it step by step:

"If something breaks in a component not used by HC, we won't care to patch it."
This makes complete sense, as I would not care about patching hexchat if I am not actually working on hexchat.

"If something breaks in a component used by HC, we'll patch it, potentially breaking something else not used by HC. Eg: patches that fix bugs in upstream, patches that revert upstream commits because they broke HC, patches that never got accepted by upstream, etc."
This part is a bit more tricky. And the reason for this was the lack of communication between downstream and upstream. I've been putting a lot of work on putting downstream patches upstream. The point here is that for quite a bit of time there was no gtk/glib maintainer who actually knew whether a win32 patch was correct or not. This has changed in the last few months where we actually fixed quite a bit of stuff upstream. Clearly some of these fixes may have produced problem in some of the changes that you have downstream. So I think we should double check the downstream patches and try to find a solution upstream.

"We'll tweak the build in ways that continue to build everything needed for HC, but maybe not anything else. Eg: removing stuff from openssl (although this particular example is a good thing), not compiling tests for projects, etc"
For this my point is I agree that you need your libraries for hexchat but the build system should allow to choose which ones should be built, so you could have a hexchat.ps1 script that calls the build.ps1 script with the right parameters in order to build hexchat and fetch the binaries that you need. And the same case for me for my own project.

"I personally don't care to increase the amount of work I put into this project, which currently is check every 2-4 weeks for updated dependencies -> download and diff their files -> update project files -> find project files are broken -> fix project files -> build everything -> [find HC is broken -> debug HC -> track down breaking commit -> fix / revert it and make a patch] -> repeat."
One of the reason I filled some of these issues was to avoid having some of these work arounds. i.e if we used the upstream msvc projects we would not need to change them in this process. Also I am all for talking with @fanc999 in case that some changes are needed upstream in order to make also our lifes easier.

"In particular, you want to build gtk3 and some new deps, and I absolutely don't want to take responsibility for fixing bugs in them."
Sounds completely fair and actually all the changes I needed in gtk/glib are already upstream.

"I am inclined to go with option 2 for the reasons I gave above, but I'm open to being convinced otherwise."
Let's go for this option for now, but I would like to take some collaboration in order to improve hexchat's main project first so we have the same script interface. i.e adding tar.xz was a must for me and I am happy that this was taken from you, apart from the great help you added here. But I think other changes would be great to take also in this project, like the upstream msvc projects, build/buildone etc.

**Comment by Arnavion** [comment] 2015-02-20 18:49
>>If something breaks in a component not used by HC, we won't care to patch it.
>This makes complete sense, as I would not care about patching hexchat if I am not actually working on hexchat.

I'm talking about patching gtk or its dependencies. If a patch is required for one of the dependencies but the bug it's fixing doesn't affect HC, I wouldn't care to merge it.

>This part is a bit more tricky. And the reason for this was the lack of communication between downstream and upstream.

Hahaha. No, the reason is that upstream is a bunch of douches. See https://bugzilla.gnome.org/show_bug.cgi?id=696505 that was closed as WONTFIX.

>So I think we should double check the downstream patches and try to find a solution upstream.

I already didn't have much of an interest in collaborating with upstream, and after the above bug was closed with that stupid reason, I've lost it completely. This may sound selfish, but I have no interest in making GTK better for everyone. I only care that HC works.

>For this my point is I agree that you need your libraries for hexchat but the build system should allow to choose which ones should be built, so you could have a hexchat.ps1 script that calls the build.ps1 script with the right parameters in order to build hexchat and fetch the binaries that you need.

There is no *should* about it. This repository is for building dependencies for HC, so that is what the build script will do. For example, that is why this repository contains openssl instead of gnutls. If HC requires that component X be built with configuration Y, then the build script will always build component X with configuration Y even if you would require it be built with configuration Z, and I see no reason to make the script more complicated to have a parameter to select configurations on a component-by-component basis.

>i.e if we used the upstream msvc projects we would not need to change them in this process.

You misunderstood. The kind of broken project files I'm talking about are usually the "someone added a new .c file but didn't add it to the project file." cases, and I've encountered more than a few in the past. And using upstream's project files doesn't help with the "find HC is broken -> debug HC -> track down breaking commit -> fix / revert it and make a patch" case, where upstream makes a Windows commit that breaks HC and then I need to track it down and revert / fix it. (And I've already explained above why this patch doesn't get sent to upstream.)

---

Here's a concrete example of what managing this repository is like.

We used to have [this patch](https://github.com/hexchat/gtk-win32/blob/5691371/pango/pango-synthesize-all-fonts.patch) for pango, because pango for some reason did not synthesize bold variants for all fonts. Why? I don't know, and the comment doesn't do a good job of explaining it, but I did know that adding this patch allowed HC to have bold versions of all fonts, so I added this patch to pango.

At one point pango supported mapping font weights to its own internal font weights. This was then [removed by Behdad](https://mail.gnome.org/archives/commits-list/2014-July/msg06643.html) for reasons unknown, which broke something in HC (I don't remember exactly what). So I made [a patch](https://github.com/hexchat/gtk-win32/blob/5691371pango/pango-normalize-font-weights.patch) to revert it. Why did he do that change? I don't know, and I don't care to find out. All I knew was that it broke HC, and reverting it fixed HC.

Eventually pango made a new commit that changes how font weights correspond to variants. Previously 500 would be considered a normal weight and so a bold variant would be synthesized for it (but only with the first patch mentioned above). But with this commit, it started being considered a bold weight itself, so it would be used for bold text. Unifont has a weight 500 variant that looks identical to the normal variant, and with this commit this variant started being used for bold text, resulting in bold text in unifont getting rendered identically to normal font. When I realized HC was no longer rendering bold text, I had to debug pango and find this code, then look in pango's commit history and find the commit that introduced it, then divine upstream's intentions for the commit, realize how it was broken and think about how to fix it, and write [a patch](https://github.com/hexchat/gtk-win32/blob/master/pango/pango-synthesize-fonts-properly.patch) to fix it properly and reintroduce the original behavior.

These are the kinds of things I sometimes have to do when I update dependencies for HC. This is why I'm not keen on adding more dependencies I'd have to maintain.

**Comment by nacho** [comment] 2015-02-21 13:26
"Hahaha. No, the reason is that upstream is a bunch of douches. See https://bugzilla.gnome.org/show_bug.cgi?id=696505 that was closed as WONTFIX." about this I understand both sides. You would like it fixed but upstream deprecated it and does not care much about fixing it. Though I am pretty sure that if you provide a patch I can review it and push it upstream if you want.

About pango or other stuff, clearly we are talking about projects that are evolving, and that can bring regressions. I do not think that is a bad thing, the bad thing would be that they would not take the patches you provide. Then again I've seen a lot of times things like this: please take thing patch because it will improve the product, without actually specifying what fixes or why it fixes it.

**Comment by nacho** [comment] 2015-02-21 14:51
Well clearly it wasn't so hard to get it upstream ;)

**Comment by nacho** [comment] 2015-02-21 15:03
For reference https://git.gnome.org/browse/gtk+/commit/?h=gtk-2-24&id=e01cc5bf5f2d1e9c0b0d1878aa6bf2cf6ad4f8ce

**Comment by TingPing** [comment] 2015-02-21 22:46
@nacho This one is a particularly bad example - https://bugzilla.gnome.org/show_bug.cgi?id=695636

It affects all users, it is reverted in every win32 distribution (here, msys2, etc), multiple users have reported so....

**Comment by TingPing** [comment] 2015-02-21 22:49
Just to put it all out there I reported https://github.com/hexchat/gtk-win32/blob/master/gtk/gtk-multimonitor.patch to LRN, who said he could not reproduce the issue on his multi-monitor setup, likely should be looked at in more detail perhaps on more setups.

**Comment by TingPing** [comment] 2015-02-21 22:50
https://bugzilla.gnome.org/show_bug.cgi?id=739835 was actually introduced by you @nacho but we never really go to any agreeable solution.

**Comment by Arnavion** [comment] 2015-02-21 23:34
>Just to put it all out there I reported https://github.com/hexchat/gtk-win32/blob/master/gtk/gtk-multimonitor.patch to LRN, who said he could not reproduce the issue on his multi-monitor setup

It'll only repro when the (0, 0) of the setup is not on the topleft-most monitor.

**Comment by TingPing** [comment] 2015-02-21 23:35
@Arnavion I can dig up the logs but I believe he did try swapping his monitors so that were the case.

**Comment by nacho** [comment] 2015-02-22 09:24
Thanks for the comments:
@TingPing  about https://bugzilla.gnome.org/show_bug.cgi?id=695636 we clearly need to do something about that, I just reopened the bug, please add some more info on the bug report.

About the multimonitor, clearly it is a problem that @LRN is not able to repro. I am pretty sure that if he would be able to repro he would manage to fix it or ack the patch.

About the regression that I introduced, sorry about that do you have any ideas on how we could improve it? Clearly we have 2 situations here though is it normal that one would install a program in C:\bin?

**Comment by nacho** [comment] 2015-02-22 09:38
If it is true that 2.24.26 fixes the first problem we would be at 2 problems to not need downstream patches I guess.

**Comment by TingPing** [comment] 2015-02-22 09:40
>I am pretty sure that if he would be able to repro he would manage to fix it or ack the patch.

Yes certainly. I am just saying why we have the patch and upstream does not.

>About the regression that I introduced, sorry about that do you have any ideas on how we could improve it?

My real issue is with the documentation. When implemented somebody wrote like 3 paragraphs explaining its behavior and what situations are not supported. You then changed the behavior to be the exact opposite of the docs which is a dubious decision for a stable api in the first place and then you didn't even update the docs to reflect that. But....

>Clearly we have 2 situations here though is it normal that one would install a program in C:\bin?

No, one user reported it and I fixed it. I don't really consider their use-case valuable but it can happen and when it does happen the behavior should at least be understandable. Likely the reason the implementation was limited in the first place.

**Comment by tomek** [comment] 2015-03-08 20:03
@nacho indeed, gtk 2.24.26 fixes that isse and we no longer need patch for it: https://github.com/hexchat/gtk-win32/commit/46f5eac7c9108381a6a038b09d47ed94f5fa572f

**Comment by Arnavion** [comment] 2016-02-01 10:11
[I have not been convinced otherwise.](https://github.com/hexchat/gtk-win32/issues/24#issuecomment-75218607)

**Closed by Arnavion** 2016-02-01 10:11 UTC
